name: Deploy to VPS

on:
  push:
    branches: [main]  # Only run on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug variables
        run: |
          echo "User: ${{ secrets.VPS_USER }}"
          echo "Host: ${{ secrets.VPS_HOST }}"
          echo "Path: ${{ secrets.VPS_PATH }}"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            if [ -d '${{ secrets.VPS_PATH }}' ]; then
              cd '${{ secrets.VPS_PATH }}' &&
              git reset --hard HEAD &&
              git pull origin main &&
              npm install &&
              pm2 restart all
            else
              echo 'ERROR: Directory ${{ secrets.VPS_PATH }} not found on VPS.'
              exit 1
            fi
          "
